version: '3.8'

services:

  fastapi-app:
    build:
      context: .
      dockerfile: docker/local.dockerfile
    container_name: fastapi_hello
    tty: true
    volumes:
      - ./app:/app
      - /app/venv
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - DATABASE_URL=mysql+aiomysql://root:password@mysql-db/testdb


  mysql-db:
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: